Fix links to make them all accessible
kedro-org/kedro pull request #1690
Opened 2022-07-05 08:59 UTC by SajidAlamQB

Signed-off-by: SajidAlamQB <90610031+SajidAlamQB@users.noreply.github.com>

## Description

Some of our links are still failing basic accessibility which is fine for now but we should fix them someday. We can adjust some just as we work on pages but should put some time aside to go through and fix them all. 

## Development notes

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

2022-07-06 03:47 UTC, deepyaman commented on docs/source/extend_kedro/common_use_cases.md
> +If you want to customise a built-in Kedro command, such as `kedro run`, for a specific project, add a `cli.py` file that defines a custom `run()` function. You should add the `cli.py` file at the sam
```suggestion
See [the template for the `cli.py` file](../development/commands_reference.md#customise-or-override-project-specific-kedro-commands).
```
Make it less of a command. :)

2022-07-06 15:40 UTC, MerelTheisenQB approved these changes
Thank you, the links have much better descriptions now! 😄

2022-07-07 22:32 UTC, deepyaman requested changes
Some questions and recommendations.

2022-07-08 08:20 UTC, yetudada reviewed
Thank you so much for this @SajidAlamQB! I agree with the changes that @deepyaman flagged.

2022-07-08 08:20 UTC, yetudada commented on docs/source/development/commands_reference.md
> +`KedroContext` can be extended in `run.py` (`src/<package_name>/run.py`). In order to use the extended `KedroContext` you need to set `context_path` in [`pyproject.toml` configuration file](../faq/ar
I think @deepyaman is correct here. And to your question, it should be 2. without the article included in the hyperlink.

2022-07-08 09:50 UTC, SajidAlamQB commented on docs/source/extend_kedro/common_use_cases.md
> +If you want to customise a built-in Kedro command, such as `kedro run`, for a specific project, add a `cli.py` file that defines a custom `run()` function. You should add the `cli.py` file at the sam
No worries, thank you for catching these out. 👍

2022-07-08 13:43 UTC, deepyaman reviewed
Thanks for making all those changes! I just took a quick pass through, but looks good for the most part.

2022-07-08 13:43 UTC, deepyaman commented on docs/source/extend_kedro/common_use_cases.md
> +To inject additional CLI commands intended to be reused across projects, please refer to [our plugins system](./plugins.md). An example of one such command is the `kedro viz` command introduced by th
```suggestion
To inject additional CLI commands intended to be reused across projects, please refer to [our plugin system](./plugins.md). An example of one such command is the `kedro viz` command introduced by the [Kedro-Viz plugin](https://github.com/kedro-org/kedro-viz). This command is intended to work on every Kedro project and therefore must be a standalone plugin.
```
(or include "official" in the link name, as when talking about starters below)

2022-07-08 13:43 UTC, deepyaman commented on docs/source/kedro_project_setup/configuration.md
> +Parameters can then be used on their own or fed in as function inputs, as described [below in Use Parameters](#use-parameters).
~Parameters can then be used on their own or fed in as function inputs, as described below in the ["Use parameters" section](#use-parameters).~

2022-07-08 13:43 UTC, deepyaman commented on docs/source/kedro_project_setup/configuration.md
> +Parameters can then be used on their own or fed in as function inputs, as described [below in Use Parameters](#use-parameters).
Better yet IMO, and avoids weird quoting:
```suggestion
[Parameters can then be used on their own or fed in as function inputs.](#use-parameters)
```

2022-07-08 13:43 UTC, deepyaman commented on docs/source/logging/experiment_tracking.md
> +The following section outlines the setup within your Kedro project to enable experiment tracking. You can also refer to the [set up experiment tracking tutorial](../tutorial/set_up_experiment_trackin
```suggestion
The following section outlines the setup within your Kedro project to enable experiment tracking. You can also refer to the [set up experiment tracking tutorial](../tutorial/experiment_tracking.md) for a step-by-step process to access your tracking datasets on Kedro-Viz.
```
or I guess you could say "tutorial on setting up experiment tracking"

2022-07-08 13:43 UTC, deepyaman commented on docs/source/tools_integration/pyspark.md
> +We recommend the following workflow, which makes use of the [Transcoding feature in Kedro](../data/data_catalog.md):
```suggestion
We recommend the following workflow, which makes use of the [transcoding feature in Kedro](../data/data_catalog.md):
```

2022-07-08 15:57 UTC, deepyaman approved these changes
🚀 🚀 🚀

2022-07-11 08:25 UTC, merged