Update deployment_guide.md
kedro-org/kedro pull request #1771
Opened 2022-08-09 12:46 UTC by noklam

## Description

## Development notes

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

2022-08-09 12:47 UTC, noklam commented
flowchart TD
    A{Can your Kedro pipeline run on a single machine?} -- YES --> B[Consult the single-machine deployment guide];
    B --> C{Do you have Docker on your machine?};
    C -- YES --> D[Use a container-based approach];
    C -- NO --> E[Use the CLI or package mode];
    A -- NO --> F[Consult the distributed deployment guide];
    F --> G["What distributed platform are you using?<br/><br/>Check out the guides for:<br/><br/><li>Argo</li><li>Prefect</li><li>Kubeflow Pipelines</li><li>AWS Batch</li><li>Databricks</li><li>Dask</li>"];
    style G text-align:left
    H["Does (part of) your pipeline integrate with Amazon SageMaker?<br/><br/>Read the SageMaker integration guide"];
    style H text-align:left

2022-08-09 12:52 UTC, noklam commented
```{mermaid}
flowchart TD
    A{Can your Kedro pipeline run on a single machine?} -- YES --> B[Consult the single-machine deployment guide];
    B --> C{Do you have Docker on your machine?};
    C -- YES --> D[Use a container-based approach];
    C -- NO --> E[Use the CLI or package mode];
    A -- NO --> F[Consult the distributed deployment guide];
    F --> G["What distributed platform are you using?<br/><br/>Check out the guides for:<br/><br/>
    <li>Argo</li>
    <li>Prefect</li>
    <li>Kubeflow Pipelines</li>
    <li>AWS Batch</li>
    <li>Databricks</li>
    <li>Dask</li>"];
    style G text-align:left
    H["Does (part of) your pipeline integrate with Amazon SageMaker?<br/><br/>Read the SageMaker integration guide"];
    style H text-align:left
```

2022-08-09 13:09 UTC, datajoely requested changes

2022-08-09 13:44 UTC, noklam commented on docs/source/deployment/deployment_guide.md
>      H["Does (part of) your pipeline integrate with Amazon SageMaker?<br/><br/>Read the SageMaker integration guide"];
@datajoely I put up a screenshot on the description, does it looks good to you?

2022-08-11 11:36 UTC, yetudada approved these changes
Thanks for this @noklam 🥳

2022-08-11 13:13 UTC, merged