docs: add kedro-partitioned plugin
kedro-org/kedro pull request #1854
Opened 2022-09-16 15:23 UTC by sbrugman

## Description
Missing this plugin in the docs

## Development notes

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro/pull/1854"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2022-09-16 20:34 UTC, deepyaman requested changes
Thanks for the PR! Minor suggestion, but aside from that, do you mind:

1. Switching the PR title to "Add `kedro-partitioned` to list of community plugins" or something (we don't use conventional commit, for better or for worse, so I wouldn't want this one to look different)
2. Fixing DCO (the instructions are there in the failed check)

2022-09-16 20:34 UTC, deepyaman commented on docs/source/extend_kedro/plugins.md
> +- [kedro-partitioned](https://github.com/ProjetaAi/kedro-partitioned), by [Gabriel Daiha Alves](https://github.com/gabrieldaiha) and [Nickolas da Rocha Machado](https://github.com/nickolasrm], extend
```suggestion
- [kedro-partitioned](https://github.com/ProjetaAi/kedro-partitioned), by [Gabriel Daiha Alves](https://github.com/gabrieldaiha) and [Nickolas da Rocha Machado](https://github.com/nickolasrm], extends the functionality for processing partitioned data
```

2022-10-06 13:44 UTC, MerelTheisenQB approved these changes
Thanks for adding this! @sbrugman 👍

2022-10-06 13:44 UTC, MerelTheisenQB commented on docs/source/extend_kedro/plugins.md
> +- [kedro-partitioned](https://github.com/ProjetaAi/kedro-partitioned), by [Gabriel Daiha Alves](https://github.com/gabrieldaiha) and [Nickolas da Rocha Machado](https://github.com/nickolasrm], extend
```suggestion
- [kedro-partitioned](https://github.com/ProjetaAi/kedro-partitioned), by [Gabriel Daiha Alves](https://github.com/gabrieldaiha) and [Nickolas da Rocha Machado](https://github.com/nickolasrm), extends the functionality on processing partitioned data.
```

2022-12-01 10:21 UTC, stichbury commented
@sbrugman  I'd like to take your suggested changes into the docs once we make the new release -- many apologies that it's taken a while to get to them. 

I can make the changes suggested for you or please could you take a look and make them yourself. I'll assume it's OK for me to proceed and merge the PR if you've not made any further changes by 8th December 2022.

Thank you again, we appreciate your contribution 🙏

2022-12-08 11:01 UTC, merged