Add documentation for preview datasets in Kedro-viz
kedro-org/kedro pull request #2773
Opened 2023-07-06 10:35 UTC by rashidakanchwala

> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Description
Add documentation for preview datasets in Kedro-viz 

## Development notes

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

2023-07-06 13:16 UTC, astrojuanlu reviewed
I didn't look at this in detail yet, commented on some whitespace and formatting issues

2023-07-06 13:16 UTC, astrojuanlu commented on docs/source/visualisation/preview_datasets.md
> +### Configure the Data Catalog
Docs build failing with

```
sphinx.errors.SphinxWarning: /home/docs/checkouts/readthedocs.org/user_builds/kedro/checkouts/2773/docs/source/visualisation/preview_datasets.md:22:Non-consecutive header level increase; H1 to H3 [myst.header]
```

So:

```suggestion
## Configure the Data Catalog
```

2023-07-06 13:16 UTC, astrojuanlu commented on docs/source/visualisation/preview_datasets.md
> +### Previewing Data on Kedro-viz
```suggestion
## Previewing Data on Kedro-viz 
```

(See above)

2023-07-06 16:16 UTC, stichbury commented on docs/source/visualisation/preview_datasets.md
> +This page describes how to preview data from different datasets in a Kedro project with Kedro-Viz. Kedro-viz currently supports preview of `CSVDatasets` and `ExcelDatasets`
> This page describes how to preview data from different datasets in a Kedro project with Kedro-Viz. Kedro-viz currently supports preview of `CSVDatasets` and `ExcelDatasets`

Please can you say what "current" is by saying something like: "Dataset preview was first introduced in Kedro-Viz version <whatever>, which offers preview for `CSVDatasets` and `ExcelDatasets`."

2023-07-06 16:18 UTC, stichbury commented on docs/source/visualisation/preview_datasets.md
> +We use the [spaceflights tutorial](../tutorial/spaceflights_tutorial.md) and demonstrate how to add data preview for the `customer`, `shuttle` and `reviews` datasets. Even if you have not yet worked
```suggestion
We use the [spaceflights tutorial](../tutorial/spaceflights_tutorial.md) to demonstrate how to add data preview for the `customer`, `shuttle` and `reviews` datasets. Even if you have not yet worked through the tutorial, you can still follow this example; you'll need to use the [Kedro starter for the spaceflights tutorial](https://github.com/kedro-org/kedro-starters/tree/main/spaceflights) to generate a copy of the project with working code in place.
```

2023-07-06 16:19 UTC, stichbury commented on docs/source/visualisation/preview_datasets.md
> +Kedro-viz currently supports preview of two types of datasets:
```suggestion
Kedro-Viz version whatever_it_is currently supports preview of two types of datasets:
```

2023-07-06 16:22 UTC, stichbury commented on docs/source/visualisation/preview_datasets.md
> +## Previewing Data on Kedro-viz
```suggestion
## Previewing Data on Kedro-viz 
```

2023-07-06 16:22 UTC, stichbury commented on docs/source/visualisation/preview_datasets.md
> +Click on each dataset node see a small preview in the metadata panel:
```suggestion
Click on each dataset node to see a small preview in the metadata panel:
```

2023-07-06 16:24 UTC, stichbury requested changes
LGTM. Just a few changes requested, mostly just small fixes to capitalisation but also please can you specify the version from which this is supported? I've made some suggestions for how to do this but you'll need to drop in the version to replace the two places I used `whatever_it_is` to represent the first version supporting the functionality.

2023-07-07 09:36 UTC, tynandebold approved these changes
Looking good!

2023-07-07 09:45 UTC, NeroOkwa commented on docs/source/visualisation/preview_datasets.md
> +To enable the preview of these datasets, you need to add the `preview_args` attribute to the `kedro-viz` configuration under the `metadata` section in the Data Catalog:
Can we also state that nrow is number of rows to be previewed?

2023-07-07 09:45 UTC, NeroOkwa approved these changes

2023-07-10 13:15 UTC, stichbury approved these changes
LGTM 🏆  Thank you!

2023-07-10 14:51 UTC, NeroOkwa approved these changes

2023-07-11 17:18 UTC, merged