Add deprecation notice to archived starters
kedro-org/kedro pull request #3173
Opened 2023-10-13 09:51 UTC by ankatiyar

> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Description

Close #3114 

## Development notes

- Show deprecation notice if the selected starter is scheduled for archiving
- Show deprecation notice when `kedro starter list` is used
- Add a message about the upcoming add-ons to `kedro new` command.

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

2023-10-13 09:59 UTC, SajidAlamQB approved these changes
LGTM, thank you @ankatiyar! 👍

2023-10-13 10:00 UTC, datajoely commented
Sorry I missed this - what is the replacement for the pyspark starter? This affects most of the QB Verticals

2023-10-13 10:06 UTC, SajidAlamQB commented
> Sorry I missed this - what is the replacement for the pyspark starter? This affects most of the QB Verticals

I believe it will be replaced by this, https://github.com/kedro-org/kedro-starters/tree/main/spaceflights-pyspark, it was introduced by @merelcht with a new suite of starters that use spaceflights as a base.

2023-10-13 10:14 UTC, merelcht commented
It would also be useful to add the deprecation mention to `kedro starter list` so the result is something like:
```
astro-airflow-iris:
  template_path: git+https://github.com/kedro-org/kedro-starters.git
  directory: astro-airflow-iris
astro-iris:
  template_path: git+https://github.com/kedro-org/kedro-starters.git
  directory: astro-airflow-iris
databricks-iris:
  template_path: git+https://github.com/kedro-org/kedro-starters.git
  directory: databricks-iris
pandas-iris (deprecated):
  template_path: git+https://github.com/kedro-org/kedro-starters.git
  directory: pandas-iris
pyspark (deprecated):
  template_path: git+https://github.com/kedro-org/kedro-starters.git
  directory: pyspark
pyspark-iris (deprecated):
  template_path: git+https://github.com/kedro-org/kedro-starters.git
  directory: pyspark-iris
spaceflights:
  template_path: git+https://github.com/kedro-org/kedro-starters.git
  directory: spaceflights
standalone-datacatalog (deprecated):
  template_path: git+https://github.com/kedro-org/kedro-starters.git
  directory: standalone-datacatalog
```

2023-10-13 10:17 UTC, datajoely commented
So I want to strongly argue we shouldn't delete the empty pyspark starter- the verticals need any empty template to build off

2023-10-13 10:26 UTC, datajoely requested changes
This would be a breaking change for many QB Vertical workflows

2023-10-13 11:12 UTC, ankatiyar commented
@datajoely I was under the impression that you can create an empty `pyspark` template with the add-ons workflow, I think @SajidAlamQB is working on it?

2023-10-13 11:14 UTC, datajoely commented
This would break the existing Alloy workflow - can you follow all the add on steps from a single command? It won't work if it's an interactive pattern.

2023-10-13 11:17 UTC, ankatiyar commented
> This would break the existing Alloy workflow - can you follow all the add on steps from a single command? It won't work if it's an interactive pattern.

Yeah, I believe it'll be `kedro new --addons=pyspark` or something like that but @SajidAlamQB @AhdraMeraliQB can comment more on it.

2023-10-13 11:18 UTC, datajoely commented
Either way it would make things a lot easier to keep this existing cookie cutter version I think

2023-10-13 11:21 UTC, datajoely commented
The main risk is that existing users refuse to go to 0.19.x because of this

2023-10-13 11:22 UTC, SajidAlamQB commented
> @datajoely I was under the impression that you can create an empty `pyspark` template with the add-ons workflow, I think @SajidAlamQB is working on it?

Yes, the new add-ons flow will have an option to create an empty `pyspark` template, and yes I believe @lrcouto is working on https://github.com/kedro-org/kedro/issues/2873 which will allow you to use add-ons from a single command.

2023-10-13 11:49 UTC, datajoely commented
I would strongly request that we keep both the pyspark and blank Kedro starters in cookiecutter format as is

2023-10-13 12:30 UTC, stichbury approved these changes
LGTM 💯

2023-10-16 14:16 UTC, merelcht commented
Discussed with the team that the deprecation warnings will still go in, because they're blocking the `0.18.14` release. I will connect with @datajoely offline to discuss the best approach of serving Alloy/verticals needs with the new project creation flow and starter structure.

2023-10-17 09:16 UTC, merged