Debugging setup of VS Code section update
kedro-org/kedro pull request #3181
Opened 2023-10-16 11:51 UTC by mustious

Signed-off-by: Mustapha Abdullahi <mustious@gmail.com>

## Description

The earlier documentation will give some users difficulty in setting up VS Code debugging with Kedro as there has been changes in VS Code UI. This PR provides a more descriptive guide to the users in setting up debugging. Following this commit (focused on the debugging), more updates will be made on the overall Kedro with VS Code setup documentation to reflect changes of VS Code UI.

## Development notes

Only documentation markdown changed.

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [x] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

2023-10-16 12:21 UTC, astrojuanlu commented
RTD failure seems unrelated: https://beta.readthedocs.org/projects/kedro/builds/22239120/#206508356--366

2023-10-16 12:23 UTC, astrojuanlu reviewed
Thanks for your PR @mustious! I left a comment

2023-10-16 15:14 UTC, mustious commented on docs/source/development/set_up_vscode.md
> +Click on the **Run and Debug** icon on the left activity bar(press `Cmd + Shift + D` for macOS). If there is no existing configuration click on **create a launch.json file** else click **Add Configur
Thanks for the kind response. I have made more changes. Kindly review :)

2023-10-16 15:51 UTC, astrojuanlu commented on docs/source/development/set_up_vscode.md
> +Click on the **Run and Debug** icon on the left activity bar(press `Cmd + Shift + D` for macOS). If there is no existing configuration, click on **create a launch.json file** else click on the Dropdo
```suggestion
Click on the **Run and Debug** icon on the left activity bar (press `Cmd + Shift + D` for macOS). If there is no existing configuration, click on **create a launch.json file** else click on the Dropdown arrow in the top-left (shown below) and click **Add Configuration** .
```

2023-10-16 15:54 UTC, astrojuanlu commented
The DCO bot is failing because commit authorship email does not match signoff email, @mustious do you mind having a look at that? You did right by signing off the commits with `-s`, but I think you have your personal email configured globally for git (you can check by doing `git config --get-all user.email`).

2023-10-16 16:21 UTC, stichbury requested changes
Requested changes noted in comment on the file

2023-10-19 14:48 UTC, mustious commented on docs/source/development/set_up_vscode.md
> +Click on the **Run and Debug** icon on the left activity bar (press `Cmd + Shift + D` for macOS). If there is no existing configuration, click on **create a launch.json file** else click on the Dropd
> Is the text **create a launch.json file** really all lower case, or is there some capitalisation?

Yes @stichbury it is all lower case. Thank you :)
![Screenshot 2023-10-19 at 15 45 46](https://github.com/kedro-org/kedro/assets/37770012/0745e894-0c95-4cd9-9a5d-e6a8534357fe)

2023-10-19 15:07 UTC, mustious commented on docs/source/development/set_up_vscode.md
> +Click on the **Run and Debug** icon on the left activity bar (press `Cmd + Shift + D` for macOS). If there is no existing configuration, click on **create a launch.json file** else click on the Dropd
I just made an update changing "Dropdown" to "dropdown". Also, it is exactly "Add Configuration" in VS Code. Please see screenshot below. Perhaps add more images will be helpful in future documentation updates. Thanks very much for the comments @stichbury :)

![Screenshot 2023-10-19 at 15 49 26](https://github.com/kedro-org/kedro/assets/37770012/9141ad1b-2c0b-4a18-aa5b-ba04c3387854)

2023-10-20 09:43 UTC, stichbury commented on docs/source/development/set_up_vscode.md
> +Click on the **Run and Debug** icon on the left activity bar (press `Cmd + Shift + D` for macOS). If there is no existing configuration, click on **create a launch.json file** else click on the dropd
```suggestion
Click on the **Run and Debug** icon on the left activity bar (press `Cmd + Shift + D` for macOS). If there is no existing configuration, click on **create a launch.json file** else click on the dropdown arrow in the top-left (shown below) and click **Add Configuration**.
```

2023-10-20 09:44 UTC, stichbury approved these changes
LGTM thanks @mustious ! 🌟

2023-10-20 12:02 UTC, astrojuanlu commented
(I'm meeting with @mustious next week to see if we can understand what's going on with the signoff 😄)

2023-10-23 11:27 UTC, mustious commented
> (I'm meeting with @mustious next week to see if we can understand what's going on with the signoff 😄)

Thanks so much @astrojuanlu for your assistance 🚀🎉

2023-10-23 11:33 UTC, astrojuanlu commented
RTD problem is unrelated:

```
sphinx.errors.SphinxWarning: /home/docs/checkouts/readthedocs.org/user_builds/kedro/checkouts/3181/docs/source/nodes_and_pipelines/pipeline_registry.md:34:broken link: https://github.com/kedro-org/kedro-starters/blob/main/spaceflights/%7B%7B%20cookiecutter.repo_name%20%7D%7D/src/%7B%7B%20cookiecutter.python_package%20%7D%7D/pipeline_registry.py (404 Client Error: Not Found for url: https://github.com/kedro-org/kedro-starters/blob/main/spaceflights/%7B%7B%20cookiecutter.repo_name%20%7D%7D/src/%7B%7B%20cookiecutter.python_package%20%7D%7D/pipeline_registry.py)
```

We will fix it separately

2023-10-24 20:15 UTC, merged