Develop
kedro-org/kedro pull request #3371
Opened 2023-11-30 12:43 UTC by rashidakanchwala

> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Description

## Development notes

Add read-the-docs-search event to Kedro's search box. 

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

2023-11-30 13:44 UTC, astrojuanlu commented
Seemingly we're still affected by this: https://github.com/readthedocs/addons/issues/205

See https://rashida-test-kedro.readthedocs.io/en/latest/

![Screen Recording 2023-11-30 at 14 41 35](https://github.com/kedro-org/kedro/assets/316517/a4b13cfe-2cc9-45f0-a36d-f6d7ec47914f)

2023-11-30 13:46 UTC, astrojuanlu commented on docs/source/_templates/layout.html
> +  document.addEventListener("DOMContentLoaded", function(event) {
We'll need to keep the `heap` stuff

2023-11-30 13:46 UTC, astrojuanlu commented on docs/source/_templates/layout.html
> +  document.addEventListener("DOMContentLoaded", function(event) {
(When we're done debugging)

2023-11-30 13:50 UTC, astrojuanlu commented
The CSS tweaks are not urgent though, they don't affect the search experience and can be done in a separate PR

2023-11-30 18:56 UTC, humitos commented
> Seemingly we're still affected by this: [readthedocs/addons#205](https://github.com/readthedocs/addons/issues/205)

Thanks for reporting this issue to us. I've fixed it and deployed a newer version. I quickly tested in your project and I'm not able to reproduce it anymore. Let me know if it's working as you expected.

2023-11-30 21:09 UTC, astrojuanlu commented
Thanks a lot @humitos! I tested it and it seems to work. Feel free to unsubscribe from this thread, we'll take it from here.

2023-12-05 12:18 UTC, astrojuanlu requested changes
Thanks a lot @rashidakanchwala 🙏🏽

2023-12-05 12:18 UTC, astrojuanlu commented on docs/source/_templates/layout.html
> +  // window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var r=document.createElement("script");r.type="text/javascript",r.async=!0,r.src="https://cdn.h
Can we restore this code? Otherwise Heap will stop receiving events. It will make your RTD builds fail, but we should be good from our side now

2023-12-05 12:18 UTC, astrojuanlu commented on docs/source/conf.py
> +# def env_override(default_appid):
Also this code

2023-12-05 12:18 UTC, astrojuanlu commented on docs/source/conf.py
> +    # app.connect("builder-inited", _add_jinja_filters)
And this

2023-12-05 12:18 UTC, astrojuanlu commented on docs/source/_templates/layout.html
> +    // Simplify the focus event listener
I'm not qualified to judge JavaScript but I hope it's fine 😅

2023-12-05 13:26 UTC, astrojuanlu commented
Reverting this to draft for now 👍🏽

2023-12-06 18:02 UTC, astrojuanlu approved these changes
I tested the two main changes:

- ✔️ The `readthedocs-search-show` event gets triggered on search box focus
- ✔️ The CSS looks exactly the same

We won't see the full effect until we enable the RTD add-ons in the project, which will happen to all versions. So, I say let's merge this PR already.

Thanks a lot @rashidakanchwala!

<img width="1512" alt="image" src="https://github.com/kedro-org/kedro/assets/316517/80936225-5986-4b7d-ba3e-4fdff2710c9b">

2023-12-11 11:18 UTC, merelcht approved these changes
Wow I didn't know this was coming, looks amazing 🤩

2023-12-11 11:27 UTC, merged