Tweak new tools/example workflow description
kedro-org/kedro pull request #3454
Opened 2023-12-20 17:53 UTC by stichbury

## Description
Created this to make a few minor tweaks to the docs about the `kedro new`workflow where tools & examples are described.

## Development notes

* Added copy to reproduce what the console says to make it easier for a reader to match up the docs and practical experience
* Added some quickstart examples as a "cheatsheet"
* Attempted to explain the example projects a little more clearly as it's super-complicated at first sight.
* Few minor formatting issues

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

2023-12-21 11:43 UTC, astrojuanlu requested changes
Nice work @stichbury - I left some comments, mainly to correct some of the quickstart one-liners but also to make the walkthrough more aligned with the current result. There's a question about how much of the actual text we want to include.

2023-12-21 11:43 UTC, astrojuanlu commented on docs/source/get_started/new_project.md
> +You can also create a new Kedro project with a starter that adds code for a common project use case. [Starters are explained separately](../starters/starters.md) later in the documentation set and th
```suggestion
You can also create a new Kedro project with a starter that adds code for a common project use case. [Starters are explained separately](../starters/starters.md) and the [spaceflights tutorial](../tutorial/tutorial_template.md) illustrates their use.
```

?

2023-12-21 11:43 UTC, astrojuanlu commented on docs/source/get_started/new_project.md
> +```
This is the output I got with `main`:

````suggestion
```text
Tools
1) Lint: Basic linting with Black and Ruff
2) Test: Basic testing with pytest
3) Log: Additional, environment-specific logging options
4) Docs: A Sphinx documentation setup
5) Data Folder: A folder structure for data management
6) PySpark: Configuration for working with PySpark
7) Kedro-Viz: Kedro's native visualisation tool

Which tools would you like to include in your project? [1-7/1,3/all/none]:
 (none): 
```
````

skipped a few intro lines:

```
Project Tools
=============
These optional tools can help you apply software engineering best practices.
To skip this step in future use --tools
To find out more: https://docs.kedro.org/en/stable/starters/new_project_tools.html
```

2023-12-21 11:43 UTC, astrojuanlu commented on docs/source/get_started/new_project.md
> +```
This is what I got from `main`:

````suggestion
```text
Would you like to include an example pipeline? :
 (no): 
```
````

Again, excluding some intro lines:

```
Example Pipeline
================
Select whether you would like an example spaceflights pipeline included in your project.
To skip this step in the future use --example=y/n
To find out more: https://docs.kedro.org/en/stable/starters/new_project_tools.html
```

2023-12-21 11:43 UTC, astrojuanlu commented on docs/source/get_started/new_project.md
> +### Quickstart examples
Really like this section 💯

2023-12-21 11:43 UTC, astrojuanlu commented on docs/source/get_started/new_project.md
> +kedro new --name=My-Project --tools=none -example=n
```suggestion
kedro new --name=My-Project --tools=none --example=n
```

2023-12-21 11:43 UTC, astrojuanlu commented on docs/source/get_started/new_project.md
> +kedro new --name=spaceflights --tools=viz -example=y
```suggestion
kedro new --name=spaceflights --tools=viz --example=y
```

2023-12-21 11:43 UTC, astrojuanlu commented on docs/source/get_started/new_project.md
> +kedro new --name=testproject --tools=Lint, Docs, PySpark -example=n
```suggestion
kedro new --name=testproject --tools=lint,docs,pyspark --example=n
```

Maybe let's make all `--tools` examples lowercase?

2023-12-21 14:33 UTC, stichbury commented
Thanks for the review @astrojuanlu -- all changes accepted.

2023-12-21 16:00 UTC, astrojuanlu approved these changes
LGTM 🚀

2023-12-21 16:51 UTC, DimedS approved these changes
Thanks, @stichbury . More clear now!

2023-12-21 17:29 UTC, stichbury commented
I could merge this but would value any insight from @AhdraMeraliQB since she worked on these docs prior to the release, and has the best context. I'll hold off on a merge until she's had a chance to feed back.

2023-12-22 12:12 UTC, AhdraMeraliQB approved these changes
These look amazing! I really like the addition of "next" and "finally" to connect how the prompts flow together, and I love the Quickstart examples section! 🌟

2023-12-22 19:03 UTC, merged