Import `TRANSCODING_SEPARATOR` to pipeline to make Kedro backwards compatible with `kedro-viz` on python 3.8
kedro-org/kedro pull request #3822
Opened 2024-04-18 13:52 UTC by ankatiyar

## Description

## Development notes

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

2024-04-18 14:40 UTC, deepyaman commented
> ### Proposed Solution 2
> * Add an import statement for `TRANSCODE_SEPARATOR` to `kedro.pipeline.pipeline`
> * **Do a patch release** to make Kedro backwards compatible with kedro-viz

How about this, but just get rid of the `_transcoding` module and put the stuff back into pipeline. TBH I think adding the `_transcoding` module wasn't really necessary, and it introduced a new convention that doesn't exist anywhere else in the codebase (modules beginning with `_`).

But generally in favor of doing a patch release; easy fix that will avoid more questions, and show responsiveness.

2024-04-18 14:54 UTC, deepyaman commented
> > ### Proposed Solution 2
> > 
> > * Add an import statement for `TRANSCODE_SEPARATOR` to `kedro.pipeline.pipeline`
> > * **Do a patch release** to make Kedro backwards compatible with kedro-viz
> 
> How about this, but just get rid of the `_transcoding` module and put the stuff back into pipeline. TBH I think adding the `_transcoding` module wasn't really necessary, and it introduced a new convention that doesn't exist anywhere else in the codebase (modules beginning with `_`).
> 
> But generally in favor of doing a patch release; easy fix that will avoid more questions, and show responsiveness.

Edit: To add some context to my suggestion—what was the original reason for moving stuff to the `_transcoding` module? The only somewhat functional thing I can see this does is make `TRANSCODING_SEPARATOR` not public (not totally sure why this is done; I have leveraged it in plugin code previously). However, if it was intentional to make this "private", then just importing it in `pipeline` undoes this, too.

2024-04-18 14:59 UTC, noklam commented
> we recently moved TRANSCODING_SEPARATOR to kedro.pipeline._transcoding.py from kedro.pipeline.pipeline.py

This is a breaking change and shouldn't be done in non-breaking release, we can do this but add a pointer to import from the new module instead. Agree with @deepyaman as I am not sure why this refactoring is necessary. It's not a big problem so a patch fix will do.

2024-04-18 15:42 UTC, merelcht commented
> To add some context to my suggestion—what was the original reason for moving stuff to the `_transcoding` module? The only somewhat functional thing I can see this does is make `TRANSCODING_SEPARATOR` not public (not totally sure why this is done; I have leveraged it in plugin code previously). However, if it was intentional to make this "private", then just importing it in `pipeline` undoes this, too.

It was done as part of https://github.com/kedro-org/kedro/pull/3812 to fix the issue with node dependencies uncovered by using the built-in toposort functionality. When reviewing it I didn't realise the transcoding separator was used outside of the framework and didn't think it was such a consequential refactor 😕

2024-04-18 16:18 UTC, ElenaKhaustova commented
We missed that when we applied #3812 😔

Given the fact that the starters' tests will keep [failing](https://github.com/kedro-org/kedro-starters/actions/runs/8739694962/job/23986559726?pr=218) until we fix that, I would go with option 2 if it's relatively fast.

2024-04-18 17:53 UTC, noklam commented on kedro/pipeline/pipeline.py
> +from ._transcoding import TRANSCODING_SEPARATOR, _strip_transcoding  # noqa: F401
```suggestion
from ._transcoding import _strip_transcoding
from ._transcoding import TRANSCODING_SEPARATOR  # noqa: F401 for 0.19.x backward compatibility
```

2024-04-18 17:53 UTC, noklam approved these changes
Approved with a small comment to explains why this is needed and remind ourselves this can be removed in 0.20

2024-04-18 18:46 UTC, deepyaman commented
> Approved with a small comment to explains why this is needed and remind ourselves this can be removed in 0.20

I think this actually shouldn't be removed in 0.20? By adding this, we're once again signaling that `TRANSCODING_SEPARATOR` is a public attribute that people can depend upon. Furthermore, my opinion is, `TRANSCODING_SEPARATOR` is something that should be exposed (it's not an internal-only implementation detail, and plugins use it, e.g. for catalog parsing).

2024-04-18 18:53 UTC, deepyaman requested changes
I'm still pushing to just get rid of the `_transcoding` module. IMO the refactor was unnecessary and inconsistent (introduced a new convention that doesn't exist anywhere else in the codebase), on top of having the breaking effect.

As mentioned in a comment just now, I don't think `TRANSCODING_SEPARATOR` should be removed from public access even in 0.20.

As such, I see this is a good time to just move the stuff back into the `pipeline` module, rather that keeping it in `_transcoding` and importing most of the stuff, anyway.

2024-04-19 10:30 UTC, merelcht approved these changes
Thanks @ankatiyar I vote to go forward with this solution.

We didn't anticipate the move to `_transcoding` to have such an impact, but nevertheless I think that was a good refactor and even though it's a new convention in Kedro it's not new for the world of Python to indicate private API in this way.

2024-04-19 10:54 UTC, merged

2024-04-19 16:24 UTC, deepyaman commented
> > @deepyaman The addition of the module is actually necessary, because it resolves a circular dependency between `node.py` and `pipeline.py`. So not really just random move, but a necessity.
> 
> There are other ways to remove circular dependencies, like not importing at the top level. It's not necessarily required.

Created a simple PR to illustrate: https://github.com/kedro-org/kedro/pull/3826