Lazy load commands from plugins
kedro-org/kedro pull request #3901
Opened 2024-05-30 11:12 UTC by ankatiyar

## Description

## Development notes

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

2024-06-03 12:08 UTC, astrojuanlu commented
To note, as @ankatiyar noted internally, "bad" lookups will take a lot of time: for example, `kedro infoo` (notice typo) took 17 seconds in my computer and tried to import kedro-viz, kedro-mlflow, and more.

Going forward, is there a smarter way we can declare new CLI commands, so that we can look them up in entry points without actually importing anything? (Feel free to open a new issue about this)

2024-06-10 13:53 UTC, ankatiyar commented
The code coverage is not complete but opening this up for review anyway to gather feedback on the method.

2024-06-11 11:16 UTC, merelcht requested changes
I added some suggestions/questions to the code, but I actually don't think it's a good idea that now the plugin commands aren't loaded when you do `kedro --help`. I've built a small plugin myself following https://docs.kedro.org/en/stable/extend_kedro/plugins.html#example-of-a-simple-plugin and the problem you get here is that the commands belong to the `kedro` group, but don't show at all. In this case there's no other top-level group you can call to see what sub-commands exist. On top of that the overwriting behaviour is changes, so if I now create my own `micropkg` command inside this kedrojson plugin it doesn't overwrite the original `kedro micropkg` where in the non lazy-loading version it does do the overwriting. 

While this solution does lead to performance gain, it also degrades the plugin command discoverability and therefore IMO usability of the plugins as a whole. Features like https://docs.kedro.org/en/stable/extend_kedro/plugins.html#global-and-project-commands will not exist anymore after this change. 

All in all, I don't think the performance gains are worth losing the plugin features.

2024-06-11 12:03 UTC, ankatiyar commented
Fair point @merelcht! 🤔 
I was also trying to implement a way where `--help` does trigger the loading of the plugins. 
About overwriting of core Kedro commands eg. `micropkg`, that might also be possible with lazy loading. Let me explore these functionalities and update the PR!

2024-06-18 12:13 UTC, ankatiyar commented
Unfortunately, I don't think the overriding behaviour of CLI is possible with lazy loading of plugins - i.e. if a plugin has overriding CLI commands for Kedro core commands such as `kedro catalog list` etc since the premise of the proposal is to only load plugins if a command does not exist in KedroCLI.
I think it's possible to trigger the loading of plugins and display plugin commands with `kedro --help` but I would like to get the team's opinions on if we should be going ahead with this at all 
cc @astrojuanlu @noklam @merelcht

2024-06-18 13:07 UTC, astrojuanlu commented
The `python` CLI has `--help` and `--help-all`. Maybe for the next breaking release we could make `--help` display only the "core" commands, and `--help-all` display everything.

For retaining the current behavior while attaining much faster load times for all the rest of commands, I'd be 👍🏼 on force-triggering loading of all plugins in `kedro --help`

2024-06-19 14:35 UTC, ankatiyar commented
Moving this back to the drafts, will close it if no other comments come in. I'll focus on getting https://github.com/kedro-org/kedro-viz/pull/1920 and https://github.com/kedro-org/kedro/pull/3883 ready for review first!

2024-06-21 08:10 UTC, closed without merging

2024-06-21 08:10 UTC, ankatiyar commented
Closing this in favour of the other solution!